version: "3.9"

services:
  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${THINKTORY_DB_USER}
      POSTGRES_PASSWORD: ${THINKTORY_DB_PASSWORD}
      POSTGRES_DB: ${THINKTORY_DB_NAME}
