version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: "mongodb"
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      - MONGO_DB_USERNAME=${MONGODB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - mongodb_data:/data/db

volumes:
  mongodb_data: